services:
  app:
      image: ghcr.io/artisandev-studio/laravel-12:latest
      container_name: app  # <--- PASTIKAN ADA
      restart: always
      env_file: 
        - .env
      volumes:
        - app-files:/var/www
      networks:
        - laravel-network  # <--- PASTIKAN ADA

  web:
      image: nginx:alpine
      container_name: web-server # <--- Tambahkan ini agar rapi
      restart: always
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - app-files:/var/www
      environment:
        - VIRTUAL_HOST=app.artisandev.web.id
        - LETSENCRYPT_HOST=app.artisandev.web.id
        - LETSENCRYPT_EMAIL=ibnudirsan@gmail.com
      networks:
        - laravel-network        # <--- WAJIB SAMA DENGAN APP
        - nginx-proxy-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

# Setup Nginx Proxy otomatis & SSL Let's Encrypt (Ini menggantikan Nginx web server di host)
  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy # <--- TAMBAHKAN INI
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - certs:/etc/nginx/certs
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
      networks:
        - nginx-proxy-network

  acme-companion:
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      environment:
        - DEFAULT_EMAIL=ibnudirsan@gmail.com # (Pastikan emailmu sudah diisi di sini)
        - NGINX_PROXY_CONTAINER=nginx-proxy  # <--- TAMBAHKAN INI
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - certs:/etc/nginx/certs
        - vhost:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - acme:/etc/acme.sh
      depends_on:
        - nginx-proxy
      networks:
        - nginx-proxy-network

networks:
  laravel-network:
    driver: bridge
  nginx-proxy-network:
    driver: bridge

volumes:
  dbdata:
  certs:
  vhost:
  html:
  acme:
  app-files:  # <--- TAMBAHKAN BARIS INI DI PALING BAWAH